### ISSUE TITLE
Weird errors since 2.530 update

### ISSUE THREAD

**Issue by Jerry-Atric** [folivoraAI/BetterTouchTool#2745]
Device - MacBook Pro Late 2016 w/TB
MacOS version - 10.12.6(16G29)
BTT version - 2.530

Ever since I updated to the 2.530 version, I get an error message every time I wake my Mac from sleep. 

It says the following: 

"Could not restart. There was an issue restarting BetterTouchTool, Please do it manually"

Even though I get the error, 9/10 times it will work perfectly without me having to do anything. Just on the off occasion, I'll have to start it up manually and it will work fine. 

Not the biggest issue but I just wanted to see if anyone else has been having the same problem and if theres a remedy out there. 
<img width="468" alt="screen shot 2018-07-03 at 16 38 35" src="https://user-images.githubusercontent.com/40889131/42375340-25daaa90-8113-11e8-9121-4a23cc1c2a54.png">
<img width="412" alt="screen shot 2018-07-03 at 05 40 16" src="https://user-images.githubusercontent.com/40889131/42375341-25fc0e9c-8113-11e8-90a9-73aef0721894.png">

**Comment by Jerry-Atric** [comment]
Anyone?

**Comment by jx22** [comment]
Also got this error. I'm on macOS 10.12.6, MacBook Pro (13-inch, 2016, Touch Bar), BTT 2.530. Not terrible but restarting the program manually as directed every time I see it -- a few times a day.

**Comment by strangewiz** [comment]
I started seeing this yesterday.  I'm on macOS 10.13.6, BTT 2.536, every time I open the lid of my macbook pro.

**Comment by fifafu** [comment]
This means the BTTRelaunch app couldn't be started for some reason. Maybe you didn't allow it on first start?
If so, open the BetterTouchTool app bundle by right-clicking it, then select "Show Package Contents" open the Contents folder and then start the BTTRelaunch app manually again. Afterwards it should be working.

**Comment by strangewiz** [comment]
I'm still seeing this issue.  I effectively ran `open /Applications/BetterTouchTool.app/Contents/Resources/BTTRelaunch.app/`.

Is there some other permission I need to allow?

**Comment by lowabr** [comment]
+1
Experiencing the same issue on two different MacBook Pro running macOS 10.12.6.
BetterTouchTool 2.536 (871)

This issue mostly happens when the Mac is woken up from sleep.

**Comment by fifafu** [comment]
@strangewiz I believe it needs to be opened via Finder to be whitelisted by macOS. The terminal open command doesn't do that.

Could you check if BTTRelaunch is running after you start BTT? It should be visible in Activity Monitor.

**Comment by strangewiz** [comment]
@fifafu I'll check next time I see the issue -- today I haven't had any problems.  FWIW I've had BTT installed for years.

**Comment by fifafu** [comment]
@strangewiz in previous versions BTT used a fallback option in case BTTRelaunch wasn't running, however that relied on a 32bit executable which I removed (it also caused various but rare issues).

**Comment by kibiz0r** [comment]
FWIW, I just ran into this and fixed it by running BTTRelaunch via Finder, as @fifafu suggested.

I had tried via Terminal beforehand, with no success. I tried invoking the binary directly, as well as using `open` on the `.app`.
